'use client';

import CopyPublicUrlButton from "@/components/prescriptions/CopyPublicUrlButton";
import ExportPrescriptionPdfButton from "@/components/prescriptions/ExportPrescriptionPdfButton";
import PrescriptionAutoPrint from "@/components/prescriptions/PrescriptionAutoPrint";
import PrescriptionPrintView, {
  type PrescriptionPrintTexts,
} from "@/components/prescriptions/PrescriptionPrintView";
import type { VisitPrescription } from "@/components/prescriptions/types";
import { useI18n } from "@/lib/i18n";
import { useState } from "react";
import Link from "next/link";
import {
  isPrivatePrescriptionPublicUrl,
  isSecurePrescriptionPublicUrl,
} from "@/utils/prescriptions/publicUrl";

type PublicPrescriptionPageClientProps = {
  prescription: VisitPrescription;
  publicUrl: string;
  isPrintMode: boolean;
};

export default function PublicPrescriptionPageClient({
  prescription,
  publicUrl,
  isPrintMode,
}: PublicPrescriptionPageClientProps) {
  const { language } = useI18n();
  const [isPrintReady, setIsPrintReady] = useState(false);
  const tr = (fr: string, en: string, ar: string) =>
    language === "ar" ? ar : language === "en" ? en : fr;
  const locale = language === "ar" ? "ar-DZ" : language === "en" ? "en-US" : "fr-FR";
  const isSecurePublicUrl = isSecurePrescriptionPublicUrl(publicUrl);
  const isPrivatePublicUrl = isPrivatePrescriptionPublicUrl(publicUrl);
  const showSecurePresentation = isSecurePublicUrl || isPrivatePublicUrl;

  const printTexts: PrescriptionPrintTexts = {
    platformTagline: tr("Plateforme Médicale", "Medical Platform", "المنصة الطبية"),
    structuredDescription: tr(
      "Ordonnance médicale structurée, générée depuis le dossier patient de la plateforme TIRYAQ.",
      "Structured medical prescription generated from the patient's record on the TIRYAQ platform.",
      "وصفة طبية منظمة تم إنشاؤها من ملف المريض على منصة TIRYAQ."
    ),
    doctorFallback: tr("Nom du docteur", "Doctor name", "اسم الطبيب"),
    specialtyFallback: tr("Spécialité", "Specialty", "التخصص"),
    addressLabel: tr("Adresse", "Address", "العنوان"),
    phoneLabel: tr("Téléphone", "Phone", "الهاتف"),
    numberLabel: tr("ID Patient", "Patient ID", "معرف المريض"),
    dateLabel: tr("Date", "Date", "التاريخ"),
    patientLabel: tr("Nom du patient", "Patient name", "اسم المريض"),
    patientFallback: tr("Patient", "Patient", "المريض"),
    observationsLabel: tr("Observations", "Notes", "ملاحظات"),
    documentLabel: tr("Document médical", "Medical document", "وثيقة طبية"),
    documentBody: tr(
      "Cette ordonnance est conservée sous forme structurée dans TIRYAQ pour faciliter l'impression, la vérification et le suivi clinique.",
      "This prescription is stored in a structured format in TIRYAQ to simplify printing, verification, and clinical follow-up.",
      "يتم حفظ هذه الوصفة بصيغة منظمة داخل TIRYAQ لتسهيل الطباعة والتحقق والمتابعة السريرية."
    ),
    signatureLabel: tr("Tampon / Signature", "Stamp / Signature", "الختم / التوقيع"),
    generatedBy: tr("Document généré par TIRYAQ", "Document generated by TIRYAQ", "مستند تم إنشاؤه بواسطة TIRYAQ"),
    securedBy: showSecurePresentation
      ? tr(
          "Sécurisé par QR Code pour vérification instantanée.",
          "Secured by QR code for instant verification.",
          "مؤمّن برمز QR للتحقق الفوري."
        )
      : tr(
          "QR Code de vérification généré. Pour un partage sécurisé, utilisez une URL HTTPS de production.",
          "Verification QR code generated. For secure sharing, use a production HTTPS URL.",
          "تم إنشاء رمز التحقق QR. للمشاركة الآمنة استخدم رابط HTTPS في بيئة الإنتاج."
        ),
    secureLinkLabel: showSecurePresentation
      ? tr("Lien sécurisé", "Secure link", "الرابط الآمن")
      : tr("Lien public", "Public link", "الرابط العام"),
    secureLinkFallback: tr(
      "Lien public disponible après enregistrement",
      "Public link available after saving",
      "الرابط العام متاح بعد الحفظ"
    ),
  };

  return (
    <main
      data-prescription-public="true"
      className="min-h-screen bg-slate-100 px-2 py-3 text-slate-900 dark:bg-slate-950 sm:px-4 sm:py-6 print:min-h-0 print:bg-white print:px-0 print:py-0"
    >
      <PrescriptionAutoPrint enabled={isPrintMode} ready={isPrintReady} />

      <div className="mx-auto mb-4 flex max-w-[920px] flex-col gap-4 print:hidden sm:mb-5 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.24em] text-blue-600">TIRYAQ</p>
          <h1 className="mt-1 text-xl font-black text-slate-950 dark:text-white sm:text-2xl">
            {showSecurePresentation
              ? tr("Copie sécurisée de l'ordonnance", "Secure prescription copy", "نسخة آمنة من الوصفة الطبية")
              : tr("Copie publique de l'ordonnance", "Public prescription copy", "نسخة عامة من الوصفة الطبية")}
          </h1>
          <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
            {tr(
              "Cette version est générée à partir des champs médicaux structurés en base.",
              "This version is generated from the structured medical fields stored in the database.",
              "تم إنشاء هذه النسخة انطلاقاً من الحقول الطبية المنظمة داخل قاعدة البيانات."
            )}
          </p>
          {!showSecurePresentation ? (
            <p className="mt-2 max-w-2xl rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-900/40 dark:bg-amber-950/30 dark:text-amber-200">
              {tr(
                "Cette copie n'utilise pas encore une URL HTTPS. Configurez une origine publique HTTPS pour sécuriser le partage.",
                "This copy is not using an HTTPS URL yet. Configure an HTTPS public origin to secure sharing.",
                "هذه النسخة لا تستخدم رابط HTTPS بعد. اضبط أصلاً عاماً عبر HTTPS لتأمين المشاركة."
              )}
            </p>
          ) : null}
        </div>

        <div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:flex-wrap sm:items-center">
          <Link
            href="/"
            className="inline-flex min-h-[48px] w-full items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 sm:w-auto"
          >
            {tr("Accueil", "Home", "الرئيسية")}
          </Link>
          <CopyPublicUrlButton
            url={publicUrl}
            label={tr("Copier le lien sécurisé", "Copy secure link", "نسخ الرابط الآمن")}
            successLabel={tr("Lien copié", "Link copied", "تم نسخ الرابط")}
            className="inline-flex min-h-[48px] w-full items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 sm:w-auto"
          />
          <ExportPrescriptionPdfButton
            prescription={prescription}
            publicUrl={publicUrl}
            texts={printTexts}
            locale={locale}
            fileName={`ordonnance-${prescription.prescription_number}.pdf`}
            label={tr("Exporter PDF", "Export PDF", "تصدير PDF")}
            exportingLabel={tr("Export en cours...", "Exporting PDF...", "جارٍ تصدير PDF...")}
            className="inline-flex min-h-[48px] w-full items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 disabled:cursor-wait disabled:opacity-70 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 sm:w-auto"
          />
          <button
            type="button"
            onClick={() => {
              if (isPrintReady) {
                window.print();
              }
            }}
            disabled={!isPrintReady}
            className="min-h-[48px] w-full rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:cursor-wait disabled:opacity-60 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200 sm:w-auto"
          >
            {isPrintReady
              ? tr("Imprimer", "Print", "طباعة")
              : tr("Préparation de l'impression...", "Preparing print...", "جارٍ تجهيز الطباعة...")}
          </button>
        </div>
      </div>

      <PrescriptionPrintView
        prescription={prescription}
        publicUrl={publicUrl}
        texts={printTexts}
        locale={locale}
        onReadyChange={setIsPrintReady}
      />
    </main>
  );
}
